

exports.uiFromJson = function(jsonFile) {
    var documentCode = `
<!-- Page generated by LopJS. -->
<!DOCTYPE html>
<html>
    <head>`
    var imports = jsonFile.imports
    var keys = Object.keys(imports)

    keys.forEach((obj) => {
        var jsonObj = imports[obj]

        var attributes = jsonObj.attributes
        var type = jsonObj.type

        documentCode += "\n        <" + type

        if(attributes !== undefined) {
            var keys1 = Object.keys(attributes)

            keys1.forEach((obj1) => {
                documentCode += ` ${obj1}="${attributes[obj1]}"`
            })
        }

        documentCode += ">" + jsonObj.value + `</${type}>`
    })

    documentCode = documentCode + `
    </head>
    
    <body>`


    
    var uiObjects = jsonFile.uiObjects
    keys = Object.keys(uiObjects)
    keys.forEach((obj) => {
        var jsonObj = uiObjects[obj]

        var attributes = jsonObj.attributes
        var type = jsonObj.type

        var code = "       <" + type

        if(attributes !== undefined) {
            var keys1 = Object.keys(attributes)

            keys1.forEach((obj1) => {
                code += ` ${obj1}="${attributes[obj1]}"`
            })
        }

        code += ">" + jsonObj.value + `</${type}>`

        documentCode += `\n ${code}`
    })

    documentCode = documentCode + `
    </body>
</html>`

    return documentCode
}