

exports.uiFromJson = function(jsonFile) {
    var documentCode = `
<!-- Page generated by LopJS. -->
<!DOCTYPE html>
<html>
    <head>`
    var imports = jsonFile.imports
    var keys = Object.keys(imports)

    keys.forEach((obj) => {
        var jsonObj = imports[obj]
        
        if(jsonObj.type == 'style') {
            documentCode = documentCode + `
        <link href="` + jsonObj.href + `" rel="stylesheet">`       
        }

        if(jsonObj.type == 'javascript') {
            documentCode = documentCode + `
        <script type="text/javascript" src="` + jsonObj.href + `"></script>`       
        }

        if(jsonObj.type == 'custom') {
            documentCode = documentCode + `
` + jsonObj.html
        }
    })

    documentCode = documentCode + `
    </head>
    
    <body>`


    
    var uiObjects = jsonFile.uiObjects
    keys = Object.keys(uiObjects)
    keys.forEach((obj) => {
        var jsonObj = uiObjects[obj]

        /** -------------------------------------------------------------------------------------------------------
         *  BUTTON TAG
         * -------------------------------------------------------------------------------------------------------
         */ 
        if(jsonObj.type == "button") {
            var type = "button"
            var string = "      <" + type + " id=\"" + obj + "\""
            
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.autofocus !== undefined) string = string + "autofocus=\"" + jsonObj.autofocus + "\" "
            if(jsonObj.form !== undefined) string = string + "form=\"" + jsonObj.form + "\" "
            if(jsonObj.formaction !== undefined) string = string + "formaction=\"" + jsonObj.formaction + "\" "
            if(jsonObj.formenctype !== undefined) string = string + "formenctype=\"" + jsonObj.formenctype + "\" "
            if(jsonObj.formmethod !== undefined) string = string + "formmethod=\"" + jsonObj.formmethod + "\" "
            if(jsonObj.formnovalidate !== undefined) string = string + "formnovalidate=\"" + jsonObj.formnovalidate + "\" "
            if(jsonObj.formtarget !== undefined) string = string + "formtarget=\"" + jsonObj.formtarget + "\" "
            if(jsonObj.name !== undefined) string = string + "name=\"" + jsonObj.name + "\" "
            if(jsonObj.type !== undefined) string = string + "type=\"" + jsonObj.type + "\" "
            if(jsonObj.value !== undefined) string = string + "value=\"" + jsonObj.value + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""


            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        /**-------------------------------------------------------------------------------------------------------
         * P TAG
         * -------------------------------------------------------------------------------------------------------
         */
        if(jsonObj.type == "text") {
            var type = "p"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        /** -------------------------------------------------------------------------------------------------------
         * B TAG
         */
        if(jsonObj.type == "bold") {
            var type = "bold"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        /** -------------------------------------------------------------------------------------------------------
         * BR TAG
         * -------------------------------------------------------------------------------------------------------
         */
        if(jsonObj.type == "br") {
            var type = "br"
            var string = "      <br/>"
            documentCode += "\n" + string
        }

        /** -------------------------------------------------------------------------------------------------------
         * H1-H6 TAGS
         * -------------------------------------------------------------------------------------------------------
         */
        if(jsonObj.type == "h1") {
            var type = "h1"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        if(jsonObj.type == "h2") {
            var type = "h2"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        if(jsonObj.type == "h3") {
            var type = "h3"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        if(jsonObj.type == "h4") {
            var type = "h4"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        if(jsonObj.type == "h5") {
            var type = "h5"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        if(jsonObj.type == "h6") {
            var type = "h6"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }

        /** -------------------------------------------------------------------------------------------------------
         * A TAG
         * -------------------------------------------------------------------------------------------------------
         */
        if(jsonObj.type == "a") {
            var onclick = false, style = false, _class = false, href = false, type = "a"
            var string = "      <" + type + " id=\"" + obj + "\""
            if(jsonObj.style !== undefined) string += " style=\"" + jsonObj.style + "\" "
            if(jsonObj.class !== undefined) string = string + "class=\"" + jsonObj.class + "\" "

            if(jsonObj.download !== undefined) string = string + "download=\"" + jsonObj.download + "\" "
            if(jsonObj.href !== undefined) string = string + "href=\"" + jsonObj.href + "\" "
            if(jsonObj.hreflang !== undefined) string = string + "hreflang=\"" + jsonObj.hreflang + "\" "
            if(jsonObj.media !== undefined) string = string + "media=\"" + jsonObj.media + "\" "
            if(jsonObj.ping !== undefined) string = string + "ping=\"" + jsonObj.ping + "\" "
            if(jsonObj.referrerpolicy !== undefined) string = string + "referrerpolicy=\"" + jsonObj.referrerpolicy + "\" "
            if(jsonObj.rel !== undefined) string = string + "rel=\"" + jsonObj.rel + "\" "
            if(jsonObj.target !== undefined) string = string + "target=\"" + jsonObj.target + "\" "
            if(jsonObj.type !== undefined) string = string + "type=\"" + jsonObj.type + "\" "

            if(jsonObj.accesskey !== undefined) string = string + "accesskey=\"" + jsonObj.accesskey + "\" "
            if(jsonObj.contenteditable !== undefined) string = string + "contenteditable=\"" + jsonObj.contenteditable + "\" "
            if(jsonObj.dir !== undefined) string = string + "dir=\"" + jsonObj.dir + "\" "
            if(jsonObj.draggable !== undefined) string = string + "draggable=\"" + jsonObj.draggable + "\" "
            if(jsonObj.hidden !== undefined) string = string + "hidden=\"" + jsonObj.hidden + "\" "
            if(jsonObj.lang !== undefined) string = string + "lang=\"" + jsonObj.lang + "\" "
            if(jsonObj.spellcheck !== undefined) string = string + "spellcheck=\"" + jsonObj.spellcheck + "\" "
            if(jsonObj.tabindex !== undefined) string = string + "tabindex=\"" + jsonObj.tabindex + "\" "
            if(jsonObj.title !== undefined) string = string + "title=\"" + jsonObj.title + "\" "
            if(jsonObj.translate !== undefined) string = string + "translate=\"" + jsonObj.translate + "\" "

            if(jsonObj.onafterprint !== undefined) string = string + "onafterprint=\"" + jsonObj.onafterprint + "\" "
            if(jsonObj.onbeforeprint !== undefined) string += "onbeforeprint=\"" + jsonObj.onbeforeprint + "\" "
            if(jsonObj.onbeforeunload !== undefined) string += "onbeforeunload=\"" + jsonObj.onbeforeunload + "\" "
            if(jsonObj.onerror !== undefined) string += "onerror=\"" + jsonObj.onerror + "\" "
            if(jsonObj.onhashchange !== undefined) string += " onhashchange=\"" + jsonObj.onhashchange + "\" "
            if(jsonObj.onload !== undefined) string += "onload=\"" + jsonObj.onload + "\" "
            if(jsonObj.onmessage !== undefined) string += "onmessage=\"" + jsonObj.onmessage + "\" "
            if(jsonObj.onoffline !== undefined) string += "onoffline=\"" + jsonObj.onoffline + "\" "
            if(jsonObj.ononline !== undefined) string += "ononline=\"" + jsonObj.ononline + "\" "
            if(jsonObj.onpagehide !== undefined) string += "onpagehide=\"" + jsonObj.onpagehide + "\" "
            if(jsonObj.onpageshow !== undefined) string += "onpageshow=\"" + jsonObj.onpageshow + "\" "
            if(jsonObj.onpopstate !== undefined) string += "onpopstate=\"" + jsonObj.onpopstate + "\" "
            if(jsonObj.onresize !== undefined) string += "onresize=\"" + jsonObj.onresize + "\" "
            if(jsonObj.onstorage !== undefined) string += "onstorage=\"" + jsonObj.onstorage + "\" "
            if(jsonObj.onunload !== undefined) string += "onunload=\"" + jsonObj.onunload + "\" "
            if(jsonObj.onkeydown !== undefined) string += "onkeydown=\"" + jsonObj.onkeydown + "\" "
            if(jsonObj.onkeypress !== undefined) string += "onkeypress=\"" + jsonObj.onkeypress + "\" "
            if(jsonObj.onkeyup !== undefined) string += "onkeyup=\"" + jsonObj.onkeyup + "\" "

            if(jsonObj.onclick !== undefined) string += "onclick=\"" + jsonObj.onclick + "\" "
            if(jsonObj.ondblclick !== undefined) string += "ondblclick=\"" + jsonObj.ondblclick + "\" "
            if(jsonObj.onmousedown !== undefined) string += "onmousedown=\"" + jsonObj.onmousedown + "\" "
            if(jsonObj.onmousemove !== undefined) string += "onmousemove=\"" + jsonObj.onmousemove + "\" "
            if(jsonObj.onmouseout !== undefined) string += "onmouseout=\"" + jsonObj.onmouseout + "\" "
            if(jsonObj.onmouseover !== undefined) string += "onmouseover=\"" + jsonObj.onmouseover + "\" "
            if(jsonObj.onmouseup !== undefined) string += "onmouseup=\"" + jsonObj.onmouseup + "\" "
            if(jsonObj.onwheel !== undefined) string += "onwheel=\"" + jsonObj.onwheel + "\" "

            if(jsonObj.ondrag !== undefined) string += "ondrag=\"" + jsonObj.ondrag + "\" "
            if(jsonObj.ondragend !== undefined) string += "ondragend=\"" + jsonObj.ondragend + "\" "
            if(jsonObj.ondragenter !== undefined) string += "ondragenter=\"" + jsonObj.ondragenter + "\" "
            if(jsonObj.ondragleave !== undefined) string += "ondragleave=\"" + jsonObj.ondragleave + "\" "
            if(jsonObj.ondragover !== undefined) string += "ondragover=\"" + jsonObj.ondragover + "\" "
            if(jsonObj.ondragstart !== undefined) string += "ondragstart=\"" + jsonObj.ondragstart + "\" "
            if(jsonObj.ondrop !== undefined) string += "ondrop=\"" + jsonObj.ondrop + "\" "
            if(jsonObj.onscroll !== undefined) string += "onscroll=\"" + jsonObj.onscroll + "\" "

            if(jsonObj.oncopy !== undefined) string += "oncopy=\"" + jsonObj.oncopy + "\" "
            if(jsonObj.oncut !== undefined) string += "oncut=\"" + jsonObj.oncut + "\" "
            if(jsonObj.onpaste !== undefined) string += "onpaste=\"" + jsonObj.onpaste + "\""
            string = string + ">" + jsonObj.text + "</" + type + ">"
            documentCode += "\n" + string
        }


    })

    documentCode = documentCode + `
    </body>
</html>`

    return documentCode
}